version: '3'
services:
  pma:
    image: phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: viblioteca
      PMA_PASSWORD: viblioteca

  notebook:
    build: ./build/jupyter
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - db
    command: start-notebook.sh --NotebookApp.token=''
