version: '3'
services:
  notebook:
    build: ./build/jupyter
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - db
    command: start-notebook.sh --NotebookApp.token=''

  db:
    image: mariadb:10.5
    ports:
      - '3306:3306'
    volumes:
      - ./build/db/dump.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
      - db-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: "viblioteca"
      MARIADB_USER: "viblioteca"
      MARIADB_PASSWORD: "viblioteca"
      MYSQL_ROOT_PASSWORD: "sekret"

  app:
    build: ./build/app
    ports:
      - '8089:5000'
    depends_on:
      - db
    working_dir: "/code"
    volumes:
      - "./volumes/app:/code"
    environment:
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "viblioteca"
      MYSQL_USER: "viblioteca"
      MYSQL_PASSWORD: "viblioteca"

  pma:
    image: phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: viblioteca
      PMA_PASSWORD: viblioteca

volumes:
  db-data:
