version: '3'
services:
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - db
    command: start-notebook.sh --NotebookApp.token=''

  db:
    image: mariadb:10.5
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE: "viblioteca"
      MARIADB_USER: "viblioteca"
      MARIADB_PASSWORD: "viblioteca"
      MYSQL_ROOT_PASSWORD: "sekret"

  pma:
    image: phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: viblioteca
      PMA_PASSWORD: viblioteca
